### ISSUE TITLE
Discussion on #Grid/Clipboard -  Selective Read-Only column

### ISSUE THREAD

**Issue by palachandra-m** [GrapeCity/wijmo-demo#14]
Can I make few columns read-only and others editable? for e.g. in above example can I make "ID" read-only and other column editable?

---
#### Grid/Clipboard

**Comment by palachandra-m** [comment]
I overlooked isReadOnly property

**Comment by banzor** [comment]
That's right. You can set isReadOnly on the entire grid (to cover all columns) or at each individual column.
